const core = require("./core")
core.plug(require("./api/auth"))
core.plug(require("./api/fs"))
core.plug(require("./api/fs-node"))
core.plug(require("./api/links"))
core.plug(require("./api/users"))
module.exports = require("./index")
